/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Biome = IDL.Variant({
  'Tropical' : IDL.Null,
  'AsteroidImpact' : IDL.Null,
  'DeepOcean' : IDL.Null,
  'Desert' : IDL.Null,
  'Volcanic' : IDL.Null,
  'Temperate' : IDL.Null,
  'Ocean' : IDL.Null,
  'Arctic' : IDL.Null,
});
export const SurveyResult = IDL.Record({
  'resourcePercentage' : IDL.Nat,
  'bonusInfo' : IDL.Opt(IDL.Text),
  'biome' : Biome,
});
export const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const ActionAuditEntry = IDL.Record({
  'action' : IDL.Text,
  'decision' : IDL.Text,
  'plotId' : IDL.Opt(IDL.Text),
  'tier' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'caller' : IDL.Principal,
  'amount' : IDL.Opt(IDL.Nat),
});
export const CombatEvent = IDL.Record({
  'attacker' : IDL.Principal,
  'intercepted' : IDL.Bool,
  'interceptorType' : IDL.Opt(IDL.Text),
  'toPlot' : IDL.Text,
  'atkPower' : IDL.Nat,
  'timestamp' : IDL.Int,
  'fromPlot' : IDL.Text,
  'success' : IDL.Bool,
  'missileType' : IDL.Opt(IDL.Text),
  'defPower' : IDL.Nat,
});
export const GeneratorTierInfo = IDL.Record({
  'name' : IDL.Text,
  'tierIndex' : IDL.Nat,
  'bonusPerDay' : IDL.Float64,
  'costFRNTR' : IDL.Nat,
});
export const EconomySnapshot = IDL.Record({
  'trigger' : IDL.Text,
  'treasuryLiquidity' : IDL.Nat,
  'activePlayers' : IDL.Nat,
  'totalPlotsOwned' : IDL.Nat,
  'treasuryDev' : IDL.Nat,
  'totalFRNTRMined' : IDL.Nat,
  'totalFRNTRBurned' : IDL.Nat,
  'timestamp' : IDL.Int,
  'globalDailyOutput' : IDL.Nat,
  'treasuryLeaderboard' : IDL.Nat,
  'totalUnclaimedFRNTR' : IDL.Nat,
});
export const FaucetClaimSummary = IDL.Record({
  'principal' : IDL.Text,
  'lastClaim' : IDL.Opt(IDL.Int),
  'totalClaims' : IDL.Nat,
});
export const GlobalStats = IDL.Record({
  'circulatingSupply' : IDL.Nat,
  'activePlayers' : IDL.Nat,
  'totalPlotsOwned' : IDL.Nat,
  'dailyEmission' : IDL.Nat,
  'totalBurned' : IDL.Nat,
});
export const MissionRequirementKind = IDL.Variant({
  'purchasePlots' : IDL.Nat,
  'upgradeToTier' : IDL.Nat,
  'holdFRNTR' : IDL.Nat,
  'reachLeaderboardTop' : IDL.Nat,
  'surveyPlot' : IDL.Null,
  'claimTokens' : IDL.Nat,
});
export const Mission = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'rewardE8s' : IDL.Nat,
  'requirement' : MissionRequirementKind,
});
export const ResourceType = IDL.Variant({
  'RareEarth' : IDL.Null,
  'Fuel' : IDL.Null,
  'Iron' : IDL.Null,
  'Crystal' : IDL.Null,
});
export const PlotProductionRate = IDL.Record({
  'totalPerDay' : IDL.Float64,
  'plotId' : IDL.Text,
  'tierBonus' : IDL.Float64,
  'baseFRNTRPerDay' : IDL.Float64,
  'generatorTier' : IDL.Nat,
  'nexusBonus' : IDL.Float64,
});
export const PrincipalDisplay = IDL.Record({
  'full' : IDL.Text,
  'short' : IDL.Text,
  'isAuthed' : IDL.Bool,
});
export const SubParcelInfo = IDL.Record({
  'resourceRate' : IDL.Float64,
  'slotIndex' : IDL.Nat,
  'isLocked' : IDL.Bool,
  'buildingType' : IDL.Text,
  'cooldownSecondsRemaining' : IDL.Nat,
});
export const SubParcel = IDL.Record({
  'subParcelId' : IDL.Text,
  'cooldownEnds' : IDL.Int,
  'plotId' : IDL.Text,
  'building' : IDL.Opt(IDL.Text),
  'slotIndex' : IDL.Nat,
  'specialization' : IDL.Text,
});
export const SurveyStatus = IDL.Variant({
  'Locked' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const PlotId = IDL.Text;
export const SurveyView = IDL.Record({
  'startTime' : IDL.Int,
  'status' : SurveyStatus,
  'result' : IDL.Opt(SurveyResult),
  'unlockCost' : IDL.Nat,
  'secondsRemaining' : IDL.Nat,
  'estimatedReward' : IDL.Nat,
  'plotId' : PlotId,
  'isCollectable' : IDL.Bool,
  'resourcePct' : IDL.Nat,
  'biome' : IDL.Text,
  'remainingSeconds' : IDL.Int,
});
export const Tokenomics = IDL.Record({
  'burnRate' : IDL.Nat,
  'emissionRate' : IDL.Nat,
  'circulatingSupply' : IDL.Nat,
  'daysUntilMilestone' : IDL.Nat,
  'totalBurned' : IDL.Nat,
  'maxSupply' : IDL.Nat,
  'remainingMineable' : IDL.Nat,
});
export const MineResult = IDL.Record({
  'efficiency' : IDL.Float64,
  'plotId' : PlotId,
  'resourceYields' : IDL.Vec(IDL.Tuple(ResourceType, IDL.Float64)),
  'frntRate' : IDL.Float64,
});
export const ResetResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const StressActionResult = IDL.Record({
  'ok' : IDL.Bool,
  'action' : IDL.Text,
  'index' : IDL.Nat,
  'errorMsg' : IDL.Opt(IDL.Text),
  'durationMs' : IDL.Int,
});
export const StressTestResult = IDL.Variant({
  'ok' : IDL.Vec(StressActionResult),
  'err' : IDL.Text,
});
export const FaucetGrant = IDL.Record({
  'icpGranted' : IDL.Nat,
  'frntGranted' : IDL.Nat,
});
export const FaucetResult = IDL.Variant({
  'ok' : FaucetGrant,
  'err' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const GeneratorTier = IDL.Variant({
  'TierIII' : IDL.Null,
  'None' : IDL.Null,
  'TierII' : IDL.Null,
  'TierIV' : IDL.Null,
  'TierVI' : IDL.Null,
  'TierI' : IDL.Null,
  'TierV' : IDL.Null,
});
export const PlotUpgradesView = IDL.Record({
  'tierName' : IDL.Text,
  'plotId' : PlotId,
  'installedAt' : IDL.Opt(Timestamp),
  'bonusPerDay' : IDL.Float64,
  'nextTierCost' : IDL.Opt(IDL.Nat),
  'generatorTier' : GeneratorTier,
});
export const UpgradeError = IDL.Variant({
  'SubParcelLocked' : IDL.Null,
  'PlotNotFound' : IDL.Null,
  'InvalidTier' : IDL.Null,
  'NotOwner' : IDL.Null,
  'AlreadyMaxTier' : IDL.Null,
  'InsufficientFRNTR' : IDL.Null,
});

export const idlService = IDL.Service({
  'assignInterceptor' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'claimAccumulatedTokens' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'claimAllPlots' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'amount' : IDL.Nat, 'plotsClaimed' : IDL.Nat }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'claimSurveyReward' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'report' : SurveyResult, 'rewardE8s' : IDL.Nat }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'completeMission' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'completeSurvey' : IDL.Func([IDL.Text], [Result], []),
  'convertICPToUSD' : IDL.Func([IDL.Nat], [IDL.Nat64], ['query']),
  'getAdjacentPlots' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getAdminInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'adminPrincipal' : IDL.Text,
          'testnestMode' : IDL.Bool,
          'totalPlots' : IDL.Nat,
          'cyclesBalance' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAdminPrincipal' : IDL.Func([], [IDL.Text], ['query']),
  'getAllPlotOwners' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getApprovedLiquidityCanister' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getAssignedInterceptor' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getAuditLogCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAuditLogForPrincipal' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Variant({
          'ok' : IDL.Vec(IDL.Tuple(IDL.Int, ActionAuditEntry)),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getCanisterCycles' : IDL.Func([], [IDL.Nat], ['query']),
  'getCombatLog' : IDL.Func([IDL.Nat], [IDL.Vec(CombatEvent)], ['query']),
  'getCoreGeneratorTiers' : IDL.Func(
      [],
      [IDL.Vec(GeneratorTierInfo)],
      ['query'],
    ),
  'getEconomySnapshots' : IDL.Func([], [IDL.Vec(EconomySnapshot)], ['query']),
  'getFaucetClaims' : IDL.Func(
      [IDL.Principal],
      [FaucetClaimSummary],
      ['query'],
    ),
  'getFirstAvailablePlot' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getFrntrLedger' : IDL.Func([], [IDL.Text], ['query']),
  'getFullAuditLog' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Vec(IDL.Tuple(IDL.Int, ActionAuditEntry)),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getGameCanisterPrincipal' : IDL.Func([], [IDL.Text], ['query']),
  'getGameStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalPlayers' : IDL.Nat,
          'totalFrntrBurned' : IDL.Nat,
          'totalActionCount' : IDL.Nat,
          'totalSupply' : IDL.Nat,
          'totalBurned' : IDL.Nat,
          'totalPlots' : IDL.Nat,
          'emissionRatePerDay' : IDL.Nat,
          'totalDailyOutput' : IDL.Nat,
          'remainingMineable' : IDL.Nat,
          'globalUnclaimedTokens' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getGeneratorTierCatalog' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'cost' : IDL.Nat,
            'tierIndex' : IDL.Nat,
            'bonusPerDay' : IDL.Float64,
          })
        ),
      ],
      ['query'],
    ),
  'getGlobalDailyOutput' : IDL.Func([], [IDL.Nat], ['query']),
  'getGlobalStats' : IDL.Func([], [GlobalStats], ['query']),
  'getGlobalUnclaimedTokens' : IDL.Func([], [IDL.Nat], ['query']),
  'getICPPrice' : IDL.Func([], [IDL.Nat64], ['query']),
  'getICPPriceUSD' : IDL.Func([], [IDL.Float64], ['query']),
  'getIcpBalance' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'getIcpUsdPrice' : IDL.Func([], [IDL.Float64], []),
  'getIcpUsdPriceCached' : IDL.Func([], [IDL.Float64], ['query']),
  'getIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'getLastSnapshotTime' : IDL.Func([], [IDL.Int], ['query']),
  'getLatestEconomySnapshot' : IDL.Func(
      [],
      [IDL.Opt(EconomySnapshot)],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Vec(
          IDL.Record({
            'principal' : IDL.Text,
            'username' : IDL.Opt(IDL.Text),
            'rank' : IDL.Nat,
            'frntBalance' : IDL.Nat,
            'plotsOwned' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getLeaderboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'leaderboardPrizePool' : IDL.Nat,
          'nextPayoutAt' : IDL.Nat,
          'activePlayers' : IDL.Nat,
          'totalPlotsOwned' : IDL.Nat,
          'totalFRNTRMined' : IDL.Nat,
          'totalFRNTRBurned' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getLivePlotOwners' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
  'getMyAuditLog' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Int, ActionAuditEntry))],
      ['query'],
    ),
  'getPassiveIncome' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getPlayerMissions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'mission' : Mission, 'completed' : IDL.Bool }))],
      ['query'],
    ),
  'getPlayerState' : IDL.Func(
      [],
      [
        IDL.Record({
          'resourceBalances' : IDL.Vec(IDL.Tuple(ResourceType, IDL.Float64)),
          'username' : IDL.Opt(IDL.Text),
          'fuel' : IDL.Nat,
          'iron' : IDL.Nat,
          'icpBalance' : IDL.Nat,
          'frntBalance' : IDL.Nat,
          'totalFRNTRBurned' : IDL.Float64,
          'plotsOwned' : IDL.Nat,
          'plotIds' : IDL.Vec(IDL.Text),
          'lastFaucetTime' : IDL.Opt(IDL.Int),
          'crystal' : IDL.Nat,
          'ownedPlots' : IDL.Vec(IDL.Text),
          'combatVictories' : IDL.Nat,
          'generatorTiersMap' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'passiveIncomePerDay' : IDL.Float64,
        }),
      ],
      [],
    ),
  'getPlayerStateByPrincipal' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'resourceBalances' : IDL.Vec(IDL.Tuple(ResourceType, IDL.Float64)),
          'username' : IDL.Opt(IDL.Text),
          'fuel' : IDL.Nat,
          'iron' : IDL.Nat,
          'icpBalance' : IDL.Nat,
          'frntBalance' : IDL.Nat,
          'totalFRNTRBurned' : IDL.Float64,
          'plotsOwned' : IDL.Nat,
          'plotIds' : IDL.Vec(IDL.Text),
          'lastFaucetTime' : IDL.Opt(IDL.Int),
          'crystal' : IDL.Nat,
          'ownedPlots' : IDL.Vec(IDL.Text),
          'combatVictories' : IDL.Nat,
          'generatorTiersMap' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'passiveIncomePerDay' : IDL.Float64,
        }),
      ],
      [],
    ),
  'getPlotCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPlotPrice' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getPlotPriceById' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getPlotProductionRate' : IDL.Func(
      [IDL.Text],
      [PlotProductionRate],
      ['query'],
    ),
  'getPlotsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
  'getPrincipal' : IDL.Func([], [PrincipalDisplay], ['query']),
  'getSubParcelStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SubParcelInfo)],
      ['query'],
    ),
  'getSubParcels' : IDL.Func([IDL.Text], [IDL.Vec(SubParcel)], ['query']),
  'getSurveyCost' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getSurveyResult' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : SurveyResult, 'err' : IDL.Text })],
      [],
    ),
  'getSurveyStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : SurveyView, 'err' : IDL.Text })],
      [],
    ),
  'getTokenomics' : IDL.Func([], [Tokenomics], ['query']),
  'getTotalBurned' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalGlobalDailyOutput' : IDL.Func([], [IDL.Nat], ['query']),
  'getTreasuryBalances' : IDL.Func(
      [],
      [
        IDL.Record({
          'leaderboardPot' : IDL.Nat,
          'devPot' : IDL.Nat,
          'liquidityPot' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getTreasuryPrincipal' : IDL.Func([], [IDL.Text], ['query']),
  'getTreasuryState' : IDL.Func(
      [],
      [
        IDL.Record({
          'leaderboard' : IDL.Nat,
          'liquidity' : IDL.Nat,
          'developer' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'initPlots' : IDL.Func(
      [
        IDL.Vec(
          IDL.Tuple(IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Nat)
        ),
      ],
      [],
      [],
    ),
  'isSubParcelLocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'launchMissile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'logCancelledAction' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Text],
      [],
      [],
    ),
  'mineResources' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : MineResult, 'err' : IDL.Text })],
      [],
    ),
  'purchasePlot' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'purgeTestPlayers' : IDL.Func([], [Result], []),
  'resetAllData' : IDL.Func([], [], []),
  'resetTestState' : IDL.Func([], [ResetResult], []),
  'setAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
  'setApprovedLiquidityCanister' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setFrntrLedger' : IDL.Func([IDL.Principal], [], []),
  'setGameCanisterPrincipal' : IDL.Func([IDL.Text], [], []),
  'setSelfPrincipal' : IDL.Func([], [], []),
  'setTreasuryPrincipal' : IDL.Func([IDL.Principal], [], []),
  'setUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'startSurvey' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : SurveyView, 'err' : IDL.Text })],
      [],
    ),
  'stressBuyPlots' : IDL.Func([IDL.Nat], [StressTestResult], []),
  'stressMintPlots' : IDL.Func([IDL.Nat], [StressTestResult], []),
  'stressUpgradePlots' : IDL.Func([IDL.Nat], [StressTestResult], []),
  'testFaucet' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'testFaucetV2' : IDL.Func([], [FaucetResult], []),
  'updateAdminPrincipalAuth' : IDL.Func([IDL.Text], [], []),
  'upgradeGenerator' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : PlotUpgradesView, 'err' : UpgradeError })],
      [],
    ),
  'withdrawLiquidityPot' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Biome = IDL.Variant({
    'Tropical' : IDL.Null,
    'AsteroidImpact' : IDL.Null,
    'DeepOcean' : IDL.Null,
    'Desert' : IDL.Null,
    'Volcanic' : IDL.Null,
    'Temperate' : IDL.Null,
    'Ocean' : IDL.Null,
    'Arctic' : IDL.Null,
  });
  const SurveyResult = IDL.Record({
    'resourcePercentage' : IDL.Nat,
    'bonusInfo' : IDL.Opt(IDL.Text),
    'biome' : Biome,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const ActionAuditEntry = IDL.Record({
    'action' : IDL.Text,
    'decision' : IDL.Text,
    'plotId' : IDL.Opt(IDL.Text),
    'tier' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'caller' : IDL.Principal,
    'amount' : IDL.Opt(IDL.Nat),
  });
  const CombatEvent = IDL.Record({
    'attacker' : IDL.Principal,
    'intercepted' : IDL.Bool,
    'interceptorType' : IDL.Opt(IDL.Text),
    'toPlot' : IDL.Text,
    'atkPower' : IDL.Nat,
    'timestamp' : IDL.Int,
    'fromPlot' : IDL.Text,
    'success' : IDL.Bool,
    'missileType' : IDL.Opt(IDL.Text),
    'defPower' : IDL.Nat,
  });
  const GeneratorTierInfo = IDL.Record({
    'name' : IDL.Text,
    'tierIndex' : IDL.Nat,
    'bonusPerDay' : IDL.Float64,
    'costFRNTR' : IDL.Nat,
  });
  const EconomySnapshot = IDL.Record({
    'trigger' : IDL.Text,
    'treasuryLiquidity' : IDL.Nat,
    'activePlayers' : IDL.Nat,
    'totalPlotsOwned' : IDL.Nat,
    'treasuryDev' : IDL.Nat,
    'totalFRNTRMined' : IDL.Nat,
    'totalFRNTRBurned' : IDL.Nat,
    'timestamp' : IDL.Int,
    'globalDailyOutput' : IDL.Nat,
    'treasuryLeaderboard' : IDL.Nat,
    'totalUnclaimedFRNTR' : IDL.Nat,
  });
  const FaucetClaimSummary = IDL.Record({
    'principal' : IDL.Text,
    'lastClaim' : IDL.Opt(IDL.Int),
    'totalClaims' : IDL.Nat,
  });
  const GlobalStats = IDL.Record({
    'circulatingSupply' : IDL.Nat,
    'activePlayers' : IDL.Nat,
    'totalPlotsOwned' : IDL.Nat,
    'dailyEmission' : IDL.Nat,
    'totalBurned' : IDL.Nat,
  });
  const MissionRequirementKind = IDL.Variant({
    'purchasePlots' : IDL.Nat,
    'upgradeToTier' : IDL.Nat,
    'holdFRNTR' : IDL.Nat,
    'reachLeaderboardTop' : IDL.Nat,
    'surveyPlot' : IDL.Null,
    'claimTokens' : IDL.Nat,
  });
  const Mission = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'rewardE8s' : IDL.Nat,
    'requirement' : MissionRequirementKind,
  });
  const ResourceType = IDL.Variant({
    'RareEarth' : IDL.Null,
    'Fuel' : IDL.Null,
    'Iron' : IDL.Null,
    'Crystal' : IDL.Null,
  });
  const PlotProductionRate = IDL.Record({
    'totalPerDay' : IDL.Float64,
    'plotId' : IDL.Text,
    'tierBonus' : IDL.Float64,
    'baseFRNTRPerDay' : IDL.Float64,
    'generatorTier' : IDL.Nat,
    'nexusBonus' : IDL.Float64,
  });
  const PrincipalDisplay = IDL.Record({
    'full' : IDL.Text,
    'short' : IDL.Text,
    'isAuthed' : IDL.Bool,
  });
  const SubParcelInfo = IDL.Record({
    'resourceRate' : IDL.Float64,
    'slotIndex' : IDL.Nat,
    'isLocked' : IDL.Bool,
    'buildingType' : IDL.Text,
    'cooldownSecondsRemaining' : IDL.Nat,
  });
  const SubParcel = IDL.Record({
    'subParcelId' : IDL.Text,
    'cooldownEnds' : IDL.Int,
    'plotId' : IDL.Text,
    'building' : IDL.Opt(IDL.Text),
    'slotIndex' : IDL.Nat,
    'specialization' : IDL.Text,
  });
  const SurveyStatus = IDL.Variant({
    'Locked' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const PlotId = IDL.Text;
  const SurveyView = IDL.Record({
    'startTime' : IDL.Int,
    'status' : SurveyStatus,
    'result' : IDL.Opt(SurveyResult),
    'unlockCost' : IDL.Nat,
    'secondsRemaining' : IDL.Nat,
    'estimatedReward' : IDL.Nat,
    'plotId' : PlotId,
    'isCollectable' : IDL.Bool,
    'resourcePct' : IDL.Nat,
    'biome' : IDL.Text,
    'remainingSeconds' : IDL.Int,
  });
  const Tokenomics = IDL.Record({
    'burnRate' : IDL.Nat,
    'emissionRate' : IDL.Nat,
    'circulatingSupply' : IDL.Nat,
    'daysUntilMilestone' : IDL.Nat,
    'totalBurned' : IDL.Nat,
    'maxSupply' : IDL.Nat,
    'remainingMineable' : IDL.Nat,
  });
  const MineResult = IDL.Record({
    'efficiency' : IDL.Float64,
    'plotId' : PlotId,
    'resourceYields' : IDL.Vec(IDL.Tuple(ResourceType, IDL.Float64)),
    'frntRate' : IDL.Float64,
  });
  const ResetResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const StressActionResult = IDL.Record({
    'ok' : IDL.Bool,
    'action' : IDL.Text,
    'index' : IDL.Nat,
    'errorMsg' : IDL.Opt(IDL.Text),
    'durationMs' : IDL.Int,
  });
  const StressTestResult = IDL.Variant({
    'ok' : IDL.Vec(StressActionResult),
    'err' : IDL.Text,
  });
  const FaucetGrant = IDL.Record({
    'icpGranted' : IDL.Nat,
    'frntGranted' : IDL.Nat,
  });
  const FaucetResult = IDL.Variant({ 'ok' : FaucetGrant, 'err' : IDL.Text });
  const Timestamp = IDL.Int;
  const GeneratorTier = IDL.Variant({
    'TierIII' : IDL.Null,
    'None' : IDL.Null,
    'TierII' : IDL.Null,
    'TierIV' : IDL.Null,
    'TierVI' : IDL.Null,
    'TierI' : IDL.Null,
    'TierV' : IDL.Null,
  });
  const PlotUpgradesView = IDL.Record({
    'tierName' : IDL.Text,
    'plotId' : PlotId,
    'installedAt' : IDL.Opt(Timestamp),
    'bonusPerDay' : IDL.Float64,
    'nextTierCost' : IDL.Opt(IDL.Nat),
    'generatorTier' : GeneratorTier,
  });
  const UpgradeError = IDL.Variant({
    'SubParcelLocked' : IDL.Null,
    'PlotNotFound' : IDL.Null,
    'InvalidTier' : IDL.Null,
    'NotOwner' : IDL.Null,
    'AlreadyMaxTier' : IDL.Null,
    'InsufficientFRNTR' : IDL.Null,
  });
  
  return IDL.Service({
    'assignInterceptor' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'claimAccumulatedTokens' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'claimAllPlots' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'amount' : IDL.Nat, 'plotsClaimed' : IDL.Nat }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'claimSurveyReward' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'report' : SurveyResult,
              'rewardE8s' : IDL.Nat,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'completeMission' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'completeSurvey' : IDL.Func([IDL.Text], [Result], []),
    'convertICPToUSD' : IDL.Func([IDL.Nat], [IDL.Nat64], ['query']),
    'getAdjacentPlots' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getAdminInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'adminPrincipal' : IDL.Text,
            'testnestMode' : IDL.Bool,
            'totalPlots' : IDL.Nat,
            'cyclesBalance' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAdminPrincipal' : IDL.Func([], [IDL.Text], ['query']),
    'getAllPlotOwners' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getApprovedLiquidityCanister' : IDL.Func(
        [],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getAssignedInterceptor' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getAuditLogCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAuditLogForPrincipal' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Variant({
            'ok' : IDL.Vec(IDL.Tuple(IDL.Int, ActionAuditEntry)),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getCanisterCycles' : IDL.Func([], [IDL.Nat], ['query']),
    'getCombatLog' : IDL.Func([IDL.Nat], [IDL.Vec(CombatEvent)], ['query']),
    'getCoreGeneratorTiers' : IDL.Func(
        [],
        [IDL.Vec(GeneratorTierInfo)],
        ['query'],
      ),
    'getEconomySnapshots' : IDL.Func([], [IDL.Vec(EconomySnapshot)], ['query']),
    'getFaucetClaims' : IDL.Func(
        [IDL.Principal],
        [FaucetClaimSummary],
        ['query'],
      ),
    'getFirstAvailablePlot' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getFrntrLedger' : IDL.Func([], [IDL.Text], ['query']),
    'getFullAuditLog' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Vec(IDL.Tuple(IDL.Int, ActionAuditEntry)),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getGameCanisterPrincipal' : IDL.Func([], [IDL.Text], ['query']),
    'getGameStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalPlayers' : IDL.Nat,
            'totalFrntrBurned' : IDL.Nat,
            'totalActionCount' : IDL.Nat,
            'totalSupply' : IDL.Nat,
            'totalBurned' : IDL.Nat,
            'totalPlots' : IDL.Nat,
            'emissionRatePerDay' : IDL.Nat,
            'totalDailyOutput' : IDL.Nat,
            'remainingMineable' : IDL.Nat,
            'globalUnclaimedTokens' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getGeneratorTierCatalog' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'cost' : IDL.Nat,
              'tierIndex' : IDL.Nat,
              'bonusPerDay' : IDL.Float64,
            })
          ),
        ],
        ['query'],
      ),
    'getGlobalDailyOutput' : IDL.Func([], [IDL.Nat], ['query']),
    'getGlobalStats' : IDL.Func([], [GlobalStats], ['query']),
    'getGlobalUnclaimedTokens' : IDL.Func([], [IDL.Nat], ['query']),
    'getICPPrice' : IDL.Func([], [IDL.Nat64], ['query']),
    'getICPPriceUSD' : IDL.Func([], [IDL.Float64], ['query']),
    'getIcpBalance' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'getIcpUsdPrice' : IDL.Func([], [IDL.Float64], []),
    'getIcpUsdPriceCached' : IDL.Func([], [IDL.Float64], ['query']),
    'getIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'getLastSnapshotTime' : IDL.Func([], [IDL.Int], ['query']),
    'getLatestEconomySnapshot' : IDL.Func(
        [],
        [IDL.Opt(EconomySnapshot)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Vec(
            IDL.Record({
              'principal' : IDL.Text,
              'username' : IDL.Opt(IDL.Text),
              'rank' : IDL.Nat,
              'frntBalance' : IDL.Nat,
              'plotsOwned' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getLeaderboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'leaderboardPrizePool' : IDL.Nat,
            'nextPayoutAt' : IDL.Nat,
            'activePlayers' : IDL.Nat,
            'totalPlotsOwned' : IDL.Nat,
            'totalFRNTRMined' : IDL.Nat,
            'totalFRNTRBurned' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getLivePlotOwners' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
    'getMyAuditLog' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Int, ActionAuditEntry))],
        ['query'],
      ),
    'getPassiveIncome' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getPlayerMissions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'mission' : Mission, 'completed' : IDL.Bool }))],
        ['query'],
      ),
    'getPlayerState' : IDL.Func(
        [],
        [
          IDL.Record({
            'resourceBalances' : IDL.Vec(IDL.Tuple(ResourceType, IDL.Float64)),
            'username' : IDL.Opt(IDL.Text),
            'fuel' : IDL.Nat,
            'iron' : IDL.Nat,
            'icpBalance' : IDL.Nat,
            'frntBalance' : IDL.Nat,
            'totalFRNTRBurned' : IDL.Float64,
            'plotsOwned' : IDL.Nat,
            'plotIds' : IDL.Vec(IDL.Text),
            'lastFaucetTime' : IDL.Opt(IDL.Int),
            'crystal' : IDL.Nat,
            'ownedPlots' : IDL.Vec(IDL.Text),
            'combatVictories' : IDL.Nat,
            'generatorTiersMap' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'passiveIncomePerDay' : IDL.Float64,
          }),
        ],
        [],
      ),
    'getPlayerStateByPrincipal' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'resourceBalances' : IDL.Vec(IDL.Tuple(ResourceType, IDL.Float64)),
            'username' : IDL.Opt(IDL.Text),
            'fuel' : IDL.Nat,
            'iron' : IDL.Nat,
            'icpBalance' : IDL.Nat,
            'frntBalance' : IDL.Nat,
            'totalFRNTRBurned' : IDL.Float64,
            'plotsOwned' : IDL.Nat,
            'plotIds' : IDL.Vec(IDL.Text),
            'lastFaucetTime' : IDL.Opt(IDL.Int),
            'crystal' : IDL.Nat,
            'ownedPlots' : IDL.Vec(IDL.Text),
            'combatVictories' : IDL.Nat,
            'generatorTiersMap' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'passiveIncomePerDay' : IDL.Float64,
          }),
        ],
        [],
      ),
    'getPlotCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPlotPrice' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getPlotPriceById' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getPlotProductionRate' : IDL.Func(
        [IDL.Text],
        [PlotProductionRate],
        ['query'],
      ),
    'getPlotsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getPrincipal' : IDL.Func([], [PrincipalDisplay], ['query']),
    'getSubParcelStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SubParcelInfo)],
        ['query'],
      ),
    'getSubParcels' : IDL.Func([IDL.Text], [IDL.Vec(SubParcel)], ['query']),
    'getSurveyCost' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getSurveyResult' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : SurveyResult, 'err' : IDL.Text })],
        [],
      ),
    'getSurveyStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : SurveyView, 'err' : IDL.Text })],
        [],
      ),
    'getTokenomics' : IDL.Func([], [Tokenomics], ['query']),
    'getTotalBurned' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalGlobalDailyOutput' : IDL.Func([], [IDL.Nat], ['query']),
    'getTreasuryBalances' : IDL.Func(
        [],
        [
          IDL.Record({
            'leaderboardPot' : IDL.Nat,
            'devPot' : IDL.Nat,
            'liquidityPot' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getTreasuryPrincipal' : IDL.Func([], [IDL.Text], ['query']),
    'getTreasuryState' : IDL.Func(
        [],
        [
          IDL.Record({
            'leaderboard' : IDL.Nat,
            'liquidity' : IDL.Nat,
            'developer' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'initPlots' : IDL.Func(
        [
          IDL.Vec(
            IDL.Tuple(IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Nat)
          ),
        ],
        [],
        [],
      ),
    'isSubParcelLocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'launchMissile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'logCancelledAction' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Text],
        [],
        [],
      ),
    'mineResources' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : MineResult, 'err' : IDL.Text })],
        [],
      ),
    'purchasePlot' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'purgeTestPlayers' : IDL.Func([], [Result], []),
    'resetAllData' : IDL.Func([], [], []),
    'resetTestState' : IDL.Func([], [ResetResult], []),
    'setAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
    'setApprovedLiquidityCanister' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setFrntrLedger' : IDL.Func([IDL.Principal], [], []),
    'setGameCanisterPrincipal' : IDL.Func([IDL.Text], [], []),
    'setSelfPrincipal' : IDL.Func([], [], []),
    'setTreasuryPrincipal' : IDL.Func([IDL.Principal], [], []),
    'setUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'startSurvey' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : SurveyView, 'err' : IDL.Text })],
        [],
      ),
    'stressBuyPlots' : IDL.Func([IDL.Nat], [StressTestResult], []),
    'stressMintPlots' : IDL.Func([IDL.Nat], [StressTestResult], []),
    'stressUpgradePlots' : IDL.Func([IDL.Nat], [StressTestResult], []),
    'testFaucet' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'testFaucetV2' : IDL.Func([], [FaucetResult], []),
    'updateAdminPrincipalAuth' : IDL.Func([IDL.Text], [], []),
    'upgradeGenerator' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : PlotUpgradesView, 'err' : UpgradeError })],
        [],
      ),
    'withdrawLiquidityPot' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };