/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActionAuditEntry {
  'action' : string,
  'decision' : string,
  'plotId' : [] | [string],
  'tier' : [] | [string],
  'timestamp' : bigint,
  'details' : string,
  'caller' : Principal,
  'amount' : [] | [bigint],
}
export type Biome = { 'Tropical' : null } |
  { 'AsteroidImpact' : null } |
  { 'DeepOcean' : null } |
  { 'Desert' : null } |
  { 'Volcanic' : null } |
  { 'Temperate' : null } |
  { 'Ocean' : null } |
  { 'Arctic' : null };
export interface CombatEvent {
  'attacker' : Principal,
  'intercepted' : boolean,
  'interceptorType' : [] | [string],
  'toPlot' : string,
  'atkPower' : bigint,
  'timestamp' : bigint,
  'fromPlot' : string,
  'success' : boolean,
  'missileType' : [] | [string],
  'defPower' : bigint,
}
export interface FaucetClaimSummary {
  'principal' : string,
  'lastClaim' : [] | [bigint],
  'totalClaims' : bigint,
}
export interface FaucetGrant { 'icpGranted' : bigint, 'frntGranted' : bigint }
export type FaucetResult = { 'ok' : FaucetGrant } |
  { 'err' : string };
export type GeneratorTier = { 'TierIII' : null } |
  { 'None' : null } |
  { 'TierII' : null } |
  { 'TierIV' : null } |
  { 'TierVI' : null } |
  { 'TierI' : null } |
  { 'TierV' : null };
export interface GeneratorTierInfo {
  'name' : string,
  'tierIndex' : bigint,
  'bonusPerDay' : number,
  'costFRNTR' : bigint,
}
export interface GlobalStats {
  'circulatingSupply' : bigint,
  'activePlayers' : bigint,
  'totalPlotsOwned' : bigint,
  'dailyEmission' : bigint,
  'totalBurned' : bigint,
}
export interface MineResult {
  'efficiency' : number,
  'plotId' : PlotId,
  'resourceYields' : Array<[ResourceType, number]>,
  'frntRate' : number,
}
export interface Mission {
  'id' : string,
  'title' : string,
  'description' : string,
  'rewardE8s' : bigint,
  'requirement' : MissionRequirementKind,
}
export type MissionRequirementKind = { 'purchasePlots' : bigint } |
  { 'upgradeToTier' : bigint } |
  { 'holdFRNTR' : bigint } |
  { 'reachLeaderboardTop' : bigint } |
  { 'surveyPlot' : null } |
  { 'claimTokens' : bigint };
export type PlotId = string;
export interface PlotProductionRate {
  'totalPerDay' : number,
  'plotId' : string,
  'tierBonus' : number,
  'baseFRNTRPerDay' : number,
  'generatorTier' : bigint,
  'nexusBonus' : number,
}
export interface PlotUpgradesView {
  'tierName' : string,
  'plotId' : PlotId,
  'installedAt' : [] | [Timestamp],
  'bonusPerDay' : number,
  'nextTierCost' : [] | [bigint],
  'generatorTier' : GeneratorTier,
}
export interface PrincipalDisplay {
  'full' : string,
  'short' : string,
  'isAuthed' : boolean,
}
export type ResetResult = { 'ok' : string } |
  { 'err' : string };
export type ResourceType = { 'RareEarth' : null } |
  { 'Fuel' : null } |
  { 'Iron' : null } |
  { 'Crystal' : null };
export type Result = { 'ok' : bigint } |
  { 'err' : string };
export interface StressActionResult {
  'ok' : boolean,
  'action' : string,
  'index' : bigint,
  'errorMsg' : [] | [string],
  'durationMs' : bigint,
}
export type StressTestResult = { 'ok' : Array<StressActionResult> } |
  { 'err' : string };
export interface SubParcel {
  'subParcelId' : string,
  'cooldownEnds' : bigint,
  'plotId' : string,
  'building' : [] | [string],
  'slotIndex' : bigint,
  'specialization' : string,
}
export interface SubParcelInfo {
  'resourceRate' : number,
  'slotIndex' : bigint,
  'isLocked' : boolean,
  'buildingType' : string,
  'cooldownSecondsRemaining' : bigint,
}
export interface SurveyResult {
  'resourcePercentage' : bigint,
  'bonusInfo' : [] | [string],
  'biome' : Biome,
}
export type SurveyStatus = { 'Locked' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export interface SurveyView {
  'startTime' : bigint,
  'status' : SurveyStatus,
  'result' : [] | [SurveyResult],
  'unlockCost' : bigint,
  'secondsRemaining' : bigint,
  'plotId' : PlotId,
}
export type Timestamp = bigint;
export interface Tokenomics {
  'burnRate' : bigint,
  'emissionRate' : bigint,
  'circulatingSupply' : bigint,
  'daysUntilMilestone' : bigint,
  'totalBurned' : bigint,
  'maxSupply' : bigint,
  'remainingMineable' : bigint,
}
export type UpgradeError = { 'SubParcelLocked' : null } |
  { 'PlotNotFound' : null } |
  { 'InvalidTier' : null } |
  { 'NotOwner' : null } |
  { 'AlreadyMaxTier' : null } |
  { 'InsufficientFRNTR' : null };
export interface _SERVICE {
  'assignInterceptor' : ActorMethod<[string, string], undefined>,
  /**
   * / Compute how much FRNTR has accrued for the caller since their lastClaimTime,
   * / transfer it from the game canister to the caller's principal via ICRC-1,
   * / update lastClaimTime to now, and return the claimed amount (in e8s) or an error.
   * / Claim accumulated FRNTR tokens for a specific plot.
   * / Accrual = (now - lastClaimTime) / 86400s * dailyRate.
   * / Mints fresh tokens via icrc1_transfer from game canister (minting account).
   */
  'claimAccumulatedTokens' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Claim accumulated FRNTR tokens for ALL plots owned by the caller.
   * / Mints fresh tokens via icrc1_transfer from game canister (minting account).
   */
  'claimAllPlots' : ActorMethod<
    [],
    { 'ok' : { 'amount' : bigint, 'plotsClaimed' : bigint } } |
      { 'err' : string }
  >,
  /**
   * / Thin wrapper around completeSurvey — returns the SurveyResult report alongside the
   * / token award so the frontend can display both in a single call.
   * / Returns #err if the survey timer is not yet complete or no survey exists.
   * / Thin wrapper around completeSurvey — returns the SurveyResult report alongside the
   * / token award so the frontend can display both in a single call.
   * / Returns #err if the survey timer is not yet complete or no survey exists.
   */
  'claimSurveyReward' : ActorMethod<
    [string],
    { 'ok' : { 'report' : SurveyResult, 'rewardE8s' : bigint } } |
      { 'err' : string }
  >,
  /**
   * / Complete a mission. Verifies requirement, mints reward, marks done.
   */
  'completeMission' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Complete a survey that has finished its timer and mint the token award to the caller.
   * / Returns #ok(awardE8s) on success or #err(message) on failure.
   */
  'completeSurvey' : ActorMethod<[string], Result>,
  'getAdjacentPlots' : ActorMethod<[string], Array<string>>,
  'getAdminPrincipal' : ActorMethod<[], string>,
  /**
   * / Returns all plots that have an owner as (plotId, ownerPrincipalText) pairs.
   */
  'getAllPlotOwners' : ActorMethod<[], Array<[string, string]>>,
  /**
   * / Returns the currently approved DEX canister principal for liquidity withdrawals.
   * / Set via setApprovedLiquidityCanister (admin only).
   */
  'getApprovedLiquidityCanister' : ActorMethod<[], [] | [string]>,
  'getAssignedInterceptor' : ActorMethod<[string], [] | [string]>,
  /**
   * / Returns the total number of entries in the audit log. Public — no auth required.
   */
  'getAuditLogCount' : ActorMethod<[], bigint>,
  /**
   * / Returns all audit log entries for a given principal.
   * / Only the principal themselves or the admin may query this.
   */
  'getAuditLogForPrincipal' : ActorMethod<
    [Principal],
    { 'ok' : Array<[bigint, ActionAuditEntry]> } |
      { 'err' : string }
  >,
  'getCombatLog' : ActorMethod<[bigint], Array<CombatEvent>>,
  'getCoreGeneratorTiers' : ActorMethod<[], Array<GeneratorTierInfo>>,
  /**
   * / Returns total faucet claims for a principal (debug/analytics).
   */
  'getFaucetClaims' : ActorMethod<[Principal], FaucetClaimSummary>,
  /**
   * / Returns the first plot ID with no owner, or null if all plots are owned.
   * / Used by the stress-test to find a purchasable plot without hardcoding an ID.
   */
  'getFirstAvailablePlot' : ActorMethod<[], [] | [string]>,
  'getFrntrLedger' : ActorMethod<[], string>,
  /**
   * / Returns the full audit log. Admin only.
   */
  'getFullAuditLog' : ActorMethod<
    [],
    { 'ok' : Array<[bigint, ActionAuditEntry]> } |
      { 'err' : string }
  >,
  'getGameCanisterPrincipal' : ActorMethod<[], string>,
  /**
   * / Live global game stats for the UNIVERSE panel (v2 — detailed fields).
   * / totalSupply = 10B hard cap (in e8s); remainingMineable = 5B mineable cap minus total burned.
   */
  'getGameStats' : ActorMethod<
    [],
    {
      'totalPlayers' : bigint,
      'totalFrntrBurned' : bigint,
      'totalActionCount' : bigint,
      'totalSupply' : bigint,
      'totalBurned' : bigint,
      'totalPlots' : bigint,
      'emissionRatePerDay' : bigint,
      'totalDailyOutput' : bigint,
      'remainingMineable' : bigint,
      'globalUnclaimedTokens' : bigint,
    }
  >,
  /**
   * / Returns the canonical generator tier catalog for all tiers.
   * / Frontend uses this so tier data is never hardcoded.
   */
  'getGeneratorTierCatalog' : ActorMethod<
    [],
    Array<{ 'cost' : bigint, 'tierIndex' : bigint, 'bonusPerDay' : number }>
  >,
  'getGlobalStats' : ActorMethod<[], GlobalStats>,
  /**
   * / Total global unclaimed tokens in e8s sitting on all owned plots.
   */
  'getGlobalUnclaimedTokens' : ActorMethod<[], bigint>,
  'getIcpBalance' : ActorMethod<[Principal], bigint>,
  /**
   * / ICP/USD price oracle — performs HTTP outcall to CoinGecko API with 60s cache.
   * / URL: https://api.coingecko.com/api/v3/simple/price?ids=internet-computer&vs_currencies=usd
   * / Returns the current ICP/USD price as a Float.
   */
  'getIcpUsdPrice' : ActorMethod<[], number>,
  /**
   * / Returns the cached ICP/USD price without an HTTP outcall.
   * / Returns 0.0 if the price has never been fetched.
   */
  'getIcpUsdPriceCached' : ActorMethod<[], number>,
  /**
   * / Returns true if the caller is the current admin principal.
   */
  'getIsAdmin' : ActorMethod<[], boolean>,
  /**
   * / Public leaderboard query: top players by FRNTR balance.
   */
  'getLeaderboard' : ActorMethod<
    [bigint],
    Array<
      {
        'principal' : string,
        'username' : [] | [string],
        'rank' : bigint,
        'frntBalance' : bigint,
        'plotsOwned' : bigint,
      }
    >
  >,
  /**
   * / Returns global leaderboard and economy stats.
   */
  'getLeaderboardStats' : ActorMethod<
    [],
    {
      'leaderboardPrizePool' : bigint,
      'nextPayoutAt' : bigint,
      'activePlayers' : bigint,
      'totalPlotsOwned' : bigint,
      'totalFRNTRMined' : bigint,
      'totalFRNTRBurned' : bigint,
    }
  >,
  /**
   * / Returns all owned plots as (plotId, ownerPrincipalText) pairs.
   * / Alias used by frontend for globe ownership sync.
   */
  'getLivePlotOwners' : ActorMethod<[], Array<[string, string]>>,
  /**
   * / Returns the full mission list.
   */
  'getMissions' : ActorMethod<[], Array<Mission>>,
  /**
   * / Returns the calling player's own audit log (most-recent-first, capped at 500 entries).
   * / No arguments required — identity is taken from the caller's principal.
   */
  'getMyAuditLog' : ActorMethod<[], Array<[bigint, ActionAuditEntry]>>,
  'getPassiveIncome' : ActorMethod<[string], number>,
  /**
   * / Returns each mission with the caller's completion status.
   */
  'getPlayerMissions' : ActorMethod<
    [],
    Array<{ 'mission' : Mission, 'completed' : boolean }>
  >,
  'getPlayerState' : ActorMethod<
    [],
    {
      'resourceBalances' : Array<[ResourceType, number]>,
      'username' : [] | [string],
      'fuel' : bigint,
      'iron' : bigint,
      'icpBalance' : bigint,
      'frntBalance' : bigint,
      'totalFRNTRBurned' : number,
      'plotsOwned' : bigint,
      'plotIds' : Array<string>,
      'lastFaucetTime' : [] | [bigint],
      'crystal' : bigint,
      'ownedPlots' : Array<string>,
      'combatVictories' : bigint,
      'generatorTiersMap' : Array<[string, bigint]>,
      'passiveIncomePerDay' : number,
    }
  >,
  /**
   * / Query the full player state for a given principal.
   * / Returns a zeroed state if the principal has not played yet.
   * / Uses live ICRC-1 ledger balance when frntrLedger is configured.
   */
  'getPlayerStateByPrincipal' : ActorMethod<
    [Principal],
    {
      'resourceBalances' : Array<[ResourceType, number]>,
      'username' : [] | [string],
      'fuel' : bigint,
      'iron' : bigint,
      'icpBalance' : bigint,
      'frntBalance' : bigint,
      'totalFRNTRBurned' : number,
      'plotsOwned' : bigint,
      'plotIds' : Array<string>,
      'lastFaucetTime' : [] | [bigint],
      'crystal' : bigint,
      'ownedPlots' : Array<string>,
      'combatVictories' : bigint,
      'generatorTiersMap' : Array<[string, bigint]>,
      'passiveIncomePerDay' : number,
    }
  >,
  /**
   * / Returns the total number of plots currently stored.
   */
  'getPlotCount' : ActorMethod<[], bigint>,
  /**
   * / Returns the canonical ICP price (e8s) for a plot identified by its H3 index.
   */
  'getPlotPrice' : ActorMethod<[string], bigint>,
  /**
   * / Returns the ICP price in e8s for a plot identified by its H3 Text ID.
   * / Price tier is derived from biome richness stored in the plots map.
   */
  'getPlotPriceById' : ActorMethod<[string], bigint>,
  'getPlotProductionRate' : ActorMethod<[string], PlotProductionRate>,
  /**
   * / Returns all plot IDs owned by a given principal.
   */
  'getPlotsByOwner' : ActorMethod<[Principal], Array<string>>,
  /**
   * / Returns the caller's principal display info for wallet/identity UI.
   */
  'getPrincipal' : ActorMethod<[], PrincipalDisplay>,
  /**
   * / Returns 7 SubParcelInfo entries (slots 0-6) for a plot.
   * / isLocked = true during the 4-hour post-purchase cooldown.
   * / cooldownSecondsRemaining = 0 when not locked.
   * / Sub-parcel ID = plotId # ":" # slotIndex.
   */
  'getSubParcelStatus' : ActorMethod<[string], Array<SubParcelInfo>>,
  /**
   * / Returns all 7 sub-parcels for a given plot ID.
   */
  'getSubParcels' : ActorMethod<[string], Array<SubParcel>>,
  /**
   * / Returns the survey cost (in FRNTR e8s) for a given plot.
   */
  'getSurveyCost' : ActorMethod<[string], bigint>,
  /**
   * / Get the completed survey result for a plot.
   * / Returns #err if the survey has not been started or the timer hasn't expired.
   */
  'getSurveyResult' : ActorMethod<
    [string],
    { 'ok' : SurveyResult } |
      { 'err' : string }
  >,
  /**
   * / Get the current survey status for a plot.
   * / If the timer has expired the result is auto-computed and the survey is
   * / promoted to #Completed — the updated record is persisted.
   */
  'getSurveyStatus' : ActorMethod<
    [string],
    { 'ok' : SurveyView } |
      { 'err' : string }
  >,
  'getTokenomics' : ActorMethod<[], Tokenomics>,
  /**
   * / Returns the total amount of FRNTR burned across all game actions.
   */
  'getTotalBurned' : ActorMethod<[], bigint>,
  /**
   * / Total global daily output in e8s across all owned plots.
   */
  'getTotalGlobalDailyOutput' : ActorMethod<[], bigint>,
  'getTreasuryBalances' : ActorMethod<
    [],
    { 'leaderboardPot' : bigint, 'devPot' : bigint, 'liquidityPot' : bigint }
  >,
  /**
   * / Query the current treasury canister principal.
   */
  'getTreasuryPrincipal' : ActorMethod<[], string>,
  /**
   * / Returns current balances of the three treasury pots in e8s.
   * / devPot: 25% of plot ICP; leaderboardPot: 25%; liquidityPot: 50%.
   * / getTreasuryState: alias for getTreasuryBalances, returns the 25/25/50 split balances.
   * / Shape: { developer: Nat; leaderboard: Nat; liquidity: Nat } (all in e8s).
   */
  'getTreasuryState' : ActorMethod<
    [],
    { 'leaderboard' : bigint, 'liquidity' : bigint, 'developer' : bigint }
  >,
  /**
   * / Seed plots from the frontend (admin only). Skips plots that already exist.
   * / Also creates 7 sub-parcels per plot (slot 0 = center Nexus, slots 1-6 = surrounding).
   */
  'initPlots' : ActorMethod<
    [Array<[string, string, number, number, bigint]>],
    undefined
  >,
  'isSubParcelLocked' : ActorMethod<[string], boolean>,
  'launchMissile' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Returns the caller's real ICP balance from the on-chain ICP ledger (ryjl3-tyaaa-aaaaa-aaaba-cai).
   * / Result is in raw e8s (divide by 100_000_000 for ICP display).
   * / Log a cancellation decision. Called by the frontend when the player clicks
   * / "Cancel" on a confirmation modal — BEFORE any canister call is made.
   * / Records the caller's wallet address, action type, and timestamp on-chain.
   */
  'logCancelledAction' : ActorMethod<
    [string, [] | [string], [] | [bigint], string],
    undefined
  >,
  /**
   * / Mine resources from an owned plot.
   * / DISABLED: returns an informative error until the mining system launches.
   */
  'mineResources' : ActorMethod<
    [string],
    { 'ok' : MineResult } |
      { 'err' : string }
  >,
  'purchasePlot' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin: wipe all game state (plots, players, usernames, faucetClaims,
   * / generatorTiers, subParcels, statsState, plotSoldCount) back to empty.
   * / Used before migrating to mainnet for a clean slate.
   */
  'resetAllData' : ActorMethod<[], undefined>,
  /**
   * / Admin: clear all player state for a clean test run (TESTNET_MODE only).
   */
  'resetTestState' : ActorMethod<[], ResetResult>,
  /**
   * / Set a new admin principal. Guarded by current admin.
   */
  'setAdminPrincipal' : ActorMethod<[Principal], undefined>,
  'setApprovedLiquidityCanister' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setFrntrLedger' : ActorMethod<[Principal], undefined>,
  'setGameCanisterPrincipal' : ActorMethod<[string], undefined>,
  'setSelfPrincipal' : ActorMethod<[], undefined>,
  /**
   * / Update the treasury canister principal (admin only).
   */
  'setTreasuryPrincipal' : ActorMethod<[Principal], undefined>,
  /**
   * / Set a unique username (3-16 alphanumeric + underscore).
   */
  'setUsername' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  /**
   * / Start a survey for a plot the caller owns.
   * / Deducts the survey cost in FRNTR (from local balance or ICRC-1 ledger) and
   * / records an in-progress survey record with startTime = now.
   * / Returns #err if the plot is not owned by the caller, if a survey is already
   * / in progress or completed, or if the caller has insufficient FRNTR.
   */
  'startSurvey' : ActorMethod<
    [string],
    { 'ok' : SurveyView } |
      { 'err' : string }
  >,
  /**
   * / Buy `count` plots in sequence (TESTNET_MODE only).
   */
  'stressBuyPlots' : ActorMethod<[bigint], StressTestResult>,
  /**
   * / Rapidly mint `count` unowned plots (TESTNET_MODE only).
   */
  'stressMintPlots' : ActorMethod<[bigint], StressTestResult>,
  /**
   * / Run `count` upgrade cycles across owned plots (TESTNET_MODE only).
   */
  'stressUpgradePlots' : ActorMethod<[bigint], StressTestResult>,
  /**
   * / Testnet faucet: grants exactly 500 FRNTR per click.
   * / No cooldown, no rate limit. ICP is real and not simulated.
   */
  'testFaucet' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  /**
   * / Testnet faucet: grants 5000 FRNTR (500_000_000_000 e8s) + 5 ICP (500_000_000 e8s) per click.
   * / Transfers FRNTR via ICRC-1 ledger (if set) and 5 ICP via ICP ledger.
   * / Auto-creates a player record if one doesn't exist.
   * / No cooldown. TESTNET_MODE=true only.
   */
  'testFaucetV2' : ActorMethod<[], FaucetResult>,
  'updateAdminPrincipalAuth' : ActorMethod<[string], undefined>,
  /**
   * / Upgrade the generator tier for an owned plot.
   * / Deducts FRNTR cost from player balance, tracks burn, sends 0.075% liquidity tax to treasury.
   */
  'upgradeGenerator' : ActorMethod<
    [string],
    { 'ok' : PlotUpgradesView } |
      { 'err' : UpgradeError }
  >,
  'withdrawLiquidityPot' : ActorMethod<
    [bigint, Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];