/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FaucetGrant {
    icpGranted: bigint;
    frntGranted: bigint;
}
export type Timestamp = bigint;
export interface StressActionResult {
    ok: boolean;
    action: string;
    index: bigint;
    errorMsg?: string;
    durationMs: bigint;
}
export interface MineResult {
    efficiency: number;
    plotId: PlotId;
    resourceYields: Array<[ResourceType, number]>;
    frntRate: number;
}
export type ResetResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface PlotUpgradesView {
    tierName: string;
    plotId: PlotId;
    installedAt?: Timestamp;
    bonusPerDay: number;
    nextTierCost?: bigint;
    generatorTier: GeneratorTier;
}
export interface SubParcel {
    subParcelId: bigint;
    cooldownEnds: bigint;
    plotId: bigint;
    building?: string;
    slotIndex: bigint;
    specialization: string;
}
export type StressTestResult = {
    __kind__: "ok";
    ok: Array<StressActionResult>;
} | {
    __kind__: "err";
    err: string;
};
export interface PrincipalDisplay {
    full: string;
    short: string;
    isAuthed: boolean;
}
export type PlotId = bigint;
export interface GeneratorTierInfo {
    name: string;
    tierIndex: bigint;
    bonusPerDay: number;
    costFRNTR: bigint;
}
export interface FaucetClaimSummary {
    principal: string;
    lastClaim?: bigint;
    totalClaims: bigint;
}
export interface SubParcelInfo {
    resourceRate: number;
    slotIndex: bigint;
    isLocked: boolean;
    buildingType: string;
    cooldownSecondsRemaining: bigint;
}
export type FaucetResult = {
    __kind__: "ok";
    ok: FaucetGrant;
} | {
    __kind__: "err";
    err: string;
};
export interface PlotProductionRate {
    totalPerDay: number;
    plotId: bigint;
    tierBonus: number;
    baseFRNTRPerDay: number;
    generatorTier: bigint;
    nexusBonus: number;
}
export interface CombatEvent {
    attacker: Principal;
    intercepted: boolean;
    interceptorType?: string;
    toPlot: bigint;
    atkPower: bigint;
    timestamp: bigint;
    fromPlot: bigint;
    success: boolean;
    missileType?: string;
    defPower: bigint;
}
export interface Tokenomics {
    burnRate: bigint;
    emissionRate: bigint;
    circulatingSupply: bigint;
    daysUntilMilestone: bigint;
    totalBurned: bigint;
    maxSupply: bigint;
    remainingMineable: bigint;
}
export interface GlobalStats {
    circulatingSupply: bigint;
    activePlayers: bigint;
    totalPlotsOwned: bigint;
    dailyEmission: bigint;
    totalBurned: bigint;
}
export enum GeneratorTier {
    TierIII = "TierIII",
    None = "None",
    TierII = "TierII",
    TierIV = "TierIV",
    TierVI = "TierVI",
    TierI = "TierI",
    TierV = "TierV"
}
export enum ResourceType {
    RareEarth = "RareEarth",
    Fuel = "Fuel",
    Iron = "Iron",
    Crystal = "Crystal"
}
export enum UpgradeError {
    SubParcelLocked = "SubParcelLocked",
    PlotNotFound = "PlotNotFound",
    InvalidTier = "InvalidTier",
    NotOwner = "NotOwner",
    AlreadyMaxTier = "AlreadyMaxTier",
    InsufficientFRNTR = "InsufficientFRNTR"
}
export interface backendInterface {
    assignInterceptor(plotId: bigint, interceptorType: string): Promise<void>;
    getAdjacentPlots(plotId: bigint): Promise<Array<bigint>>;
    getAdminPrincipal(): Promise<string>;
    /**
     * / Returns all plots that have an owner as (plotId, ownerPrincipalText) pairs.
     */
    getAllPlotOwners(): Promise<Array<[bigint, string]>>;
    getAssignedInterceptor(plotId: bigint): Promise<string | null>;
    getCombatLog(limit: bigint): Promise<Array<CombatEvent>>;
    getCoreGeneratorTiers(): Promise<Array<GeneratorTierInfo>>;
    /**
     * / Returns total faucet claims for a principal (debug/analytics).
     */
    getFaucetClaims(principal: Principal): Promise<FaucetClaimSummary>;
    /**
     * / Returns the first plot ID with no owner, or null if all plots are owned.
     * / Used by the stress-test to find a purchasable plot without hardcoding an ID.
     */
    getFirstAvailablePlot(): Promise<bigint | null>;
    getFrntrLedger(): Promise<string>;
    getGameCanisterPrincipal(): Promise<string>;
    /**
     * / Live global game stats for the UNIVERSE panel (v2 — detailed fields).
     * / totalSupply = 10B hard cap; remainingMineable = 5B mineable cap minus total burned.
     */
    getGameStats(): Promise<{
        totalPlayers: bigint;
        totalFrntrBurned: bigint;
        totalSupply: bigint;
        totalBurned: bigint;
        totalPlots: bigint;
        emissionRatePerDay: bigint;
        remainingMineable: bigint;
    }>;
    getGlobalStats(): Promise<GlobalStats>;
    /**
     * / ICP/USD price oracle — performs HTTP outcall to CoinGecko API with 60s cache.
     * / URL: https://api.coingecko.com/api/v3/simple/price?ids=internet-computer&vs_currencies=usd
     * / Returns the current ICP/USD price as a Float.
     */
    getIcpUsdPrice(): Promise<number>;
    /**
     * / Returns the cached ICP/USD price without an HTTP outcall.
     * / Returns 0.0 if the price has never been fetched.
     */
    getIcpUsdPriceCached(): Promise<number>;
    /**
     * / Public leaderboard query: top players by FRNTR balance.
     */
    getLeaderboard(limit: bigint): Promise<Array<{
        principal: string;
        username?: string;
        rank: bigint;
        frntBalance: bigint;
        plotsOwned: bigint;
    }>>;
    /**
     * / Returns global leaderboard and economy stats.
     */
    getLeaderboardStats(): Promise<{
        leaderboardPrizePool: bigint;
        nextPayoutAt: bigint;
        activePlayers: bigint;
        totalPlotsOwned: bigint;
        totalFRNTRMined: bigint;
        totalFRNTRBurned: bigint;
    }>;
    getPassiveIncome(plotId: bigint): Promise<number>;
    getPlayerState(): Promise<{
        resourceBalances: Array<[ResourceType, number]>;
        username?: string;
        fuel: bigint;
        iron: bigint;
        frntBalance: bigint;
        totalFRNTRBurned: number;
        plotsOwned: bigint;
        lastFaucetTime?: bigint;
        crystal: bigint;
        ownedPlots: Array<string>;
        combatVictories: bigint;
        generatorTiersMap: Array<[string, bigint]>;
        passiveIncomePerDay: number;
    }>;
    /**
     * / Query the full player state for a given principal.
     * / Returns a zeroed state if the principal has not played yet.
     */
    getPlayerStateByPrincipal(principal: Principal): Promise<{
        resourceBalances: Array<[ResourceType, number]>;
        username?: string;
        fuel: bigint;
        iron: bigint;
        frntBalance: bigint;
        totalFRNTRBurned: number;
        plotsOwned: bigint;
        lastFaucetTime?: bigint;
        crystal: bigint;
        ownedPlots: Array<string>;
        combatVictories: bigint;
        generatorTiersMap: Array<[string, bigint]>;
        passiveIncomePerDay: number;
    }>;
    /**
     * / Returns the total number of plots currently stored.
     */
    getPlotCount(): Promise<bigint>;
    /**
     * / Returns the canonical ICP price (e8s) for a plot identified by its H3 index.
     */
    getPlotPrice(h3Index: string): Promise<bigint>;
    /**
     * / Returns the ICP price in e8s for a plot identified by its numeric plot ID.
     * / Price tier is derived from biome richness stored in the plots map.
     */
    getPlotPriceById(plotId: bigint): Promise<bigint>;
    getPlotProductionRate(plotId: bigint): Promise<PlotProductionRate>;
    /**
     * / Returns all plot IDs owned by a given principal.
     */
    getPlotsByOwner(owner: Principal): Promise<Array<bigint>>;
    /**
     * / Returns the caller's principal display info for wallet/identity UI.
     */
    getPrincipal(): Promise<PrincipalDisplay>;
    /**
     * / Returns 7 SubParcelInfo entries (slots 0-6) for a plot.
     * / isLocked = true during the 4-hour post-purchase cooldown.
     * / cooldownSecondsRemaining = 0 when not locked.
     * / Sub-parcel ID = plotId * 10 + slotIndex.
     */
    getSubParcelStatus(plotId: bigint): Promise<Array<SubParcelInfo>>;
    /**
     * / Returns all 7 sub-parcels for a given plot ID.
     */
    getSubParcels(plotId: bigint): Promise<Array<SubParcel>>;
    getTokenomics(): Promise<Tokenomics>;
    getTreasuryBalances(): Promise<{
        leaderboardPot: bigint;
        devPot: bigint;
        liquidityPot: bigint;
    }>;
    /**
     * / Query the current treasury canister principal.
     */
    getTreasuryPrincipal(): Promise<string>;
    /**
     * / Returns current balances of the three treasury pots in e8s.
     * / devPot: 25% of plot ICP; leaderboardPot: 25%; liquidityPot: 50%.
     * / getTreasuryState: alias for getTreasuryBalances, returns the 25/25/50 split balances.
     * / Shape: { developer: Nat; leaderboard: Nat; liquidity: Nat } (all in e8s).
     */
    getTreasuryState(): Promise<{
        leaderboard: bigint;
        liquidity: bigint;
        developer: bigint;
    }>;
    /**
     * / Seed plots from the frontend (admin only). Skips plots that already exist.
     * / Also creates 7 sub-parcels per plot (slot 0 = center Nexus, slots 1-6 = surrounding).
     */
    initPlots(plotData: Array<[bigint, string, number, number, bigint]>): Promise<void>;
    isSubParcelLocked(plotId: bigint): Promise<boolean>;
    launchMissile(fromPlotId: bigint, toPlotId: bigint, missileType: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Mine resources from an owned plot.
     */
    mineResources(plotId: bigint): Promise<{
        __kind__: "ok";
        ok: MineResult;
    } | {
        __kind__: "err";
        err: string;
    }>;
    purchasePlot(plotId: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Admin: wipe all game state (plots, players, usernames, faucetClaims,
     * / generatorTiers, subParcels, statsState, plotSoldCount) back to empty.
     * / Used before migrating to mainnet for a clean slate.
     */
    resetAllData(): Promise<void>;
    /**
     * / Admin: clear all player state for a clean test run (TESTNET_MODE only).
     */
    resetTestState(): Promise<ResetResult>;
    /**
     * / Set a new admin principal. Guarded by current admin.
     */
    setAdminPrincipal(p: Principal): Promise<void>;
    setApprovedLiquidityCanister(dexCanister: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setFrntrLedger(canisterId: Principal): Promise<void>;
    setGameCanisterPrincipal(p: string): Promise<void>;
    setSelfPrincipal(): Promise<void>;
    /**
     * / Update the treasury canister principal (admin only).
     */
    setTreasuryPrincipal(p: Principal): Promise<void>;
    /**
     * / Set a unique username (3-16 alphanumeric + underscore).
     */
    setUsername(username: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Buy `count` plots in sequence (TESTNET_MODE only).
     */
    stressBuyPlots(count: bigint): Promise<StressTestResult>;
    /**
     * / Rapidly mint `count` unowned plots (TESTNET_MODE only).
     */
    stressMintPlots(count: bigint): Promise<StressTestResult>;
    /**
     * / Run `count` upgrade cycles across owned plots (TESTNET_MODE only).
     */
    stressUpgradePlots(count: bigint): Promise<StressTestResult>;
    /**
     * / Testnet faucet: grants exactly 500 FRNTR per click.
     * / No cooldown, no rate limit. ICP is real and not simulated.
     */
    testFaucet(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Testnet faucet: grants 500 FRNTR + 2 ICP (simulated) per click.
     * / No cooldown, no auth check beyond TESTNET_MODE=true.
     * / Testnet faucet: grants 500 FRNTR + 2 ICP (simulated) per click.
     * / Auto-creates a player record (600 FRNTR seed) if one doesn't exist.
     * / No cooldown, no auth check beyond TESTNET_MODE=true.
     */
    testFaucetV2(): Promise<FaucetResult>;
    updateAdminPrincipalAuth(newPrincipal: string): Promise<void>;
    /**
     * / Upgrade the generator tier for an owned plot.
     * / Deducts FRNTR cost from player balance, tracks burn, sends 0.075% liquidity tax to treasury.
     */
    upgradeGenerator(plotId: bigint): Promise<{
        __kind__: "ok";
        ok: PlotUpgradesView;
    } | {
        __kind__: "err";
        err: UpgradeError;
    }>;
    withdrawLiquidityPot(amountE8s: bigint, recipient: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { CombatEvent as _CombatEvent, FaucetClaimSummary as _FaucetClaimSummary, FaucetGrant as _FaucetGrant, FaucetResult as _FaucetResult, GeneratorTier as _GeneratorTier, MineResult as _MineResult, PlotId as _PlotId, PlotUpgradesView as _PlotUpgradesView, ResetResult as _ResetResult, ResourceType as _ResourceType, StressActionResult as _StressActionResult, StressTestResult as _StressTestResult, SubParcel as _SubParcel, Timestamp as _Timestamp, UpgradeError as _UpgradeError } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignInterceptor(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignInterceptor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignInterceptor(arg0, arg1);
            return result;
        }
    }
    async getAdjacentPlots(arg0: bigint): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdjacentPlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdjacentPlots(arg0);
            return result;
        }
    }
    async getAdminPrincipal(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipal();
            return result;
        }
    }
    async getAllPlotOwners(): Promise<Array<[bigint, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlotOwners();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlotOwners();
            return result;
        }
    }
    async getAssignedInterceptor(arg0: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignedInterceptor(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignedInterceptor(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCombatLog(arg0: bigint): Promise<Array<CombatEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCombatLog(arg0);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCombatLog(arg0);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoreGeneratorTiers(): Promise<Array<GeneratorTierInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoreGeneratorTiers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoreGeneratorTiers();
            return result;
        }
    }
    async getFaucetClaims(arg0: Principal): Promise<FaucetClaimSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getFaucetClaims(arg0);
                return from_candid_FaucetClaimSummary_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFaucetClaims(arg0);
            return from_candid_FaucetClaimSummary_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFirstAvailablePlot(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFirstAvailablePlot();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFirstAvailablePlot();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFrntrLedger(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getFrntrLedger();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFrntrLedger();
            return result;
        }
    }
    async getGameCanisterPrincipal(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameCanisterPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameCanisterPrincipal();
            return result;
        }
    }
    async getGameStats(): Promise<{
        totalPlayers: bigint;
        totalFrntrBurned: bigint;
        totalSupply: bigint;
        totalBurned: bigint;
        totalPlots: bigint;
        emissionRatePerDay: bigint;
        remainingMineable: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameStats();
            return result;
        }
    }
    async getGlobalStats(): Promise<GlobalStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalStats();
            return result;
        }
    }
    async getIcpUsdPrice(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getIcpUsdPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIcpUsdPrice();
            return result;
        }
    }
    async getIcpUsdPriceCached(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getIcpUsdPriceCached();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIcpUsdPriceCached();
            return result;
        }
    }
    async getLeaderboard(arg0: bigint): Promise<Array<{
        principal: string;
        username?: string;
        rank: bigint;
        frntBalance: bigint;
        plotsOwned: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboardStats(): Promise<{
        leaderboardPrizePool: bigint;
        nextPayoutAt: bigint;
        activePlayers: bigint;
        totalPlotsOwned: bigint;
        totalFRNTRMined: bigint;
        totalFRNTRBurned: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboardStats();
            return result;
        }
    }
    async getPassiveIncome(arg0: bigint): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getPassiveIncome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPassiveIncome(arg0);
            return result;
        }
    }
    async getPlayerState(): Promise<{
        resourceBalances: Array<[ResourceType, number]>;
        username?: string;
        fuel: bigint;
        iron: bigint;
        frntBalance: bigint;
        totalFRNTRBurned: number;
        plotsOwned: bigint;
        lastFaucetTime?: bigint;
        crystal: bigint;
        ownedPlots: Array<string>;
        combatVictories: bigint;
        generatorTiersMap: Array<[string, bigint]>;
        passiveIncomePerDay: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerState();
                return from_candid_record_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerState();
            return from_candid_record_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerStateByPrincipal(arg0: Principal): Promise<{
        resourceBalances: Array<[ResourceType, number]>;
        username?: string;
        fuel: bigint;
        iron: bigint;
        frntBalance: bigint;
        totalFRNTRBurned: number;
        plotsOwned: bigint;
        lastFaucetTime?: bigint;
        crystal: bigint;
        ownedPlots: Array<string>;
        combatVictories: bigint;
        generatorTiersMap: Array<[string, bigint]>;
        passiveIncomePerDay: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerStateByPrincipal(arg0);
                return from_candid_record_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerStateByPrincipal(arg0);
            return from_candid_record_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlotCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlotCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlotCount();
            return result;
        }
    }
    async getPlotPrice(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlotPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlotPrice(arg0);
            return result;
        }
    }
    async getPlotPriceById(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlotPriceById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlotPriceById(arg0);
            return result;
        }
    }
    async getPlotProductionRate(arg0: bigint): Promise<PlotProductionRate> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlotProductionRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlotProductionRate(arg0);
            return result;
        }
    }
    async getPlotsByOwner(arg0: Principal): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlotsByOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlotsByOwner(arg0);
            return result;
        }
    }
    async getPrincipal(): Promise<PrincipalDisplay> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrincipal();
            return result;
        }
    }
    async getSubParcelStatus(arg0: bigint): Promise<Array<SubParcelInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubParcelStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubParcelStatus(arg0);
            return result;
        }
    }
    async getSubParcels(arg0: bigint): Promise<Array<SubParcel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubParcels(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubParcels(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTokenomics(): Promise<Tokenomics> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenomics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenomics();
            return result;
        }
    }
    async getTreasuryBalances(): Promise<{
        leaderboardPot: bigint;
        devPot: bigint;
        liquidityPot: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreasuryBalances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreasuryBalances();
            return result;
        }
    }
    async getTreasuryPrincipal(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreasuryPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreasuryPrincipal();
            return result;
        }
    }
    async getTreasuryState(): Promise<{
        leaderboard: bigint;
        liquidity: bigint;
        developer: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreasuryState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreasuryState();
            return result;
        }
    }
    async initPlots(arg0: Array<[bigint, string, number, number, bigint]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initPlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initPlots(arg0);
            return result;
        }
    }
    async isSubParcelLocked(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSubParcelLocked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSubParcelLocked(arg0);
            return result;
        }
    }
    async launchMissile(arg0: bigint, arg1: bigint, arg2: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.launchMissile(arg0, arg1, arg2);
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.launchMissile(arg0, arg1, arg2);
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async mineResources(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: MineResult;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.mineResources(arg0);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mineResources(arg0);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchasePlot(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.purchasePlot(arg0);
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchasePlot(arg0);
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAllData();
            return result;
        }
    }
    async resetTestState(): Promise<ResetResult> {
        if (this.processError) {
            try {
                const result = await this.actor.resetTestState();
                return from_candid_ResetResult_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetTestState();
            return from_candid_ResetResult_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdminPrincipal(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminPrincipal(arg0);
            return result;
        }
    }
    async setApprovedLiquidityCanister(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setApprovedLiquidityCanister(arg0);
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApprovedLiquidityCanister(arg0);
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async setFrntrLedger(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFrntrLedger(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFrntrLedger(arg0);
            return result;
        }
    }
    async setGameCanisterPrincipal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGameCanisterPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGameCanisterPrincipal(arg0);
            return result;
        }
    }
    async setSelfPrincipal(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSelfPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSelfPrincipal();
            return result;
        }
    }
    async setTreasuryPrincipal(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTreasuryPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTreasuryPrincipal(arg0);
            return result;
        }
    }
    async setUsername(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setUsername(arg0);
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUsername(arg0);
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async stressBuyPlots(arg0: bigint): Promise<StressTestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.stressBuyPlots(arg0);
                return from_candid_StressTestResult_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stressBuyPlots(arg0);
            return from_candid_StressTestResult_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async stressMintPlots(arg0: bigint): Promise<StressTestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.stressMintPlots(arg0);
                return from_candid_StressTestResult_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stressMintPlots(arg0);
            return from_candid_StressTestResult_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async stressUpgradePlots(arg0: bigint): Promise<StressTestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.stressUpgradePlots(arg0);
                return from_candid_StressTestResult_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stressUpgradePlots(arg0);
            return from_candid_StressTestResult_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async testFaucet(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.testFaucet();
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.testFaucet();
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async testFaucetV2(): Promise<FaucetResult> {
        if (this.processError) {
            try {
                const result = await this.actor.testFaucetV2();
                return from_candid_FaucetResult_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.testFaucetV2();
            return from_candid_FaucetResult_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAdminPrincipalAuth(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminPrincipalAuth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminPrincipalAuth(arg0);
            return result;
        }
    }
    async upgradeGenerator(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: PlotUpgradesView;
    } | {
        __kind__: "err";
        err: UpgradeError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeGenerator(arg0);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeGenerator(arg0);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async withdrawLiquidityPot(arg0: bigint, arg1: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawLiquidityPot(arg0, arg1);
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawLiquidityPot(arg0, arg1);
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CombatEvent_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CombatEvent): CombatEvent {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_FaucetClaimSummary_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FaucetClaimSummary): FaucetClaimSummary {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_FaucetResult_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FaucetResult): FaucetResult {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_GeneratorTier_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GeneratorTier): GeneratorTier {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_MineResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MineResult): MineResult {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PlotUpgradesView_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlotUpgradesView): PlotUpgradesView {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ResetResult_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResetResult): ResetResult {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceType): ResourceType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_StressActionResult_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StressActionResult): StressActionResult {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_StressTestResult_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StressTestResult): StressTestResult {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_SubParcel_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubParcel): SubParcel {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UpgradeError_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpgradeError): UpgradeError {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: string;
    username: [] | [string];
    rank: bigint;
    frntBalance: bigint;
    plotsOwned: bigint;
}): {
    principal: string;
    username?: string;
    rank: bigint;
    frntBalance: bigint;
    plotsOwned: bigint;
} {
    return {
        principal: value.principal,
        username: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.username)),
        rank: value.rank,
        frntBalance: value.frntBalance,
        plotsOwned: value.plotsOwned
    };
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resourceBalances: Array<[_ResourceType, number]>;
    username: [] | [string];
    fuel: bigint;
    iron: bigint;
    frntBalance: bigint;
    totalFRNTRBurned: number;
    plotsOwned: bigint;
    lastFaucetTime: [] | [bigint];
    crystal: bigint;
    ownedPlots: Array<string>;
    combatVictories: bigint;
    generatorTiersMap: Array<[string, bigint]>;
    passiveIncomePerDay: number;
}): {
    resourceBalances: Array<[ResourceType, number]>;
    username?: string;
    fuel: bigint;
    iron: bigint;
    frntBalance: bigint;
    totalFRNTRBurned: number;
    plotsOwned: bigint;
    lastFaucetTime?: bigint;
    crystal: bigint;
    ownedPlots: Array<string>;
    combatVictories: bigint;
    generatorTiersMap: Array<[string, bigint]>;
    passiveIncomePerDay: number;
} {
    return {
        resourceBalances: from_candid_vec_n12(_uploadFile, _downloadFile, value.resourceBalances),
        username: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.username)),
        fuel: value.fuel,
        iron: value.iron,
        frntBalance: value.frntBalance,
        totalFRNTRBurned: value.totalFRNTRBurned,
        plotsOwned: value.plotsOwned,
        lastFaucetTime: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.lastFaucetTime)),
        crystal: value.crystal,
        ownedPlots: value.ownedPlots,
        combatVictories: value.combatVictories,
        generatorTiersMap: value.generatorTiersMap,
        passiveIncomePerDay: value.passiveIncomePerDay
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subParcelId: bigint;
    cooldownEnds: bigint;
    plotId: bigint;
    building: [] | [string];
    slotIndex: bigint;
    specialization: string;
}): {
    subParcelId: bigint;
    cooldownEnds: bigint;
    plotId: bigint;
    building?: string;
    slotIndex: bigint;
    specialization: string;
} {
    return {
        subParcelId: value.subParcelId,
        cooldownEnds: value.cooldownEnds,
        plotId: value.plotId,
        building: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.building)),
        slotIndex: value.slotIndex,
        specialization: value.specialization
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    efficiency: number;
    plotId: _PlotId;
    resourceYields: Array<[_ResourceType, number]>;
    frntRate: number;
}): {
    efficiency: number;
    plotId: PlotId;
    resourceYields: Array<[ResourceType, number]>;
    frntRate: number;
} {
    return {
        efficiency: value.efficiency,
        plotId: value.plotId,
        resourceYields: from_candid_vec_n12(_uploadFile, _downloadFile, value.resourceYields),
        frntRate: value.frntRate
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
    action: string;
    index: bigint;
    errorMsg: [] | [string];
    durationMs: bigint;
}): {
    ok: boolean;
    action: string;
    index: bigint;
    errorMsg?: string;
    durationMs: bigint;
} {
    return {
        ok: value.ok,
        action: value.action,
        index: value.index,
        errorMsg: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.errorMsg)),
        durationMs: value.durationMs
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tierName: string;
    plotId: _PlotId;
    installedAt: [] | [_Timestamp];
    bonusPerDay: number;
    nextTierCost: [] | [bigint];
    generatorTier: _GeneratorTier;
}): {
    tierName: string;
    plotId: PlotId;
    installedAt?: Timestamp;
    bonusPerDay: number;
    nextTierCost?: bigint;
    generatorTier: GeneratorTier;
} {
    return {
        tierName: value.tierName,
        plotId: value.plotId,
        installedAt: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.installedAt)),
        bonusPerDay: value.bonusPerDay,
        nextTierCost: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.nextTierCost)),
        generatorTier: from_candid_GeneratorTier_n36(_uploadFile, _downloadFile, value.generatorTier)
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    attacker: Principal;
    intercepted: boolean;
    interceptorType: [] | [string];
    toPlot: bigint;
    atkPower: bigint;
    timestamp: bigint;
    fromPlot: bigint;
    success: boolean;
    missileType: [] | [string];
    defPower: bigint;
}): {
    attacker: Principal;
    intercepted: boolean;
    interceptorType?: string;
    toPlot: bigint;
    atkPower: bigint;
    timestamp: bigint;
    fromPlot: bigint;
    success: boolean;
    missileType?: string;
    defPower: bigint;
} {
    return {
        attacker: value.attacker,
        intercepted: value.intercepted,
        interceptorType: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.interceptorType)),
        toPlot: value.toPlot,
        atkPower: value.atkPower,
        timestamp: value.timestamp,
        fromPlot: value.fromPlot,
        success: value.success,
        missileType: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.missileType)),
        defPower: value.defPower
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: string;
    lastClaim: [] | [bigint];
    totalClaims: bigint;
}): {
    principal: string;
    lastClaim?: bigint;
    totalClaims: bigint;
} {
    return {
        principal: value.principal,
        lastClaim: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.lastClaim)),
        totalClaims: value.totalClaims
    };
}
function from_candid_tuple_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ResourceType, number]): [ResourceType, number] {
    return [
        from_candid_ResourceType_n14(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    RareEarth: null;
} | {
    Fuel: null;
} | {
    Iron: null;
} | {
    Crystal: null;
}): ResourceType {
    return "RareEarth" in value ? ResourceType.RareEarth : "Fuel" in value ? ResourceType.Fuel : "Iron" in value ? ResourceType.Iron : "Crystal" in value ? ResourceType.Crystal : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MineResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: MineResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_MineResult_n21(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_StressActionResult>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<StressActionResult>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n27(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _FaucetGrant;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: FaucetGrant;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PlotUpgradesView;
} | {
    err: _UpgradeError;
}): {
    __kind__: "ok";
    ok: PlotUpgradesView;
} | {
    __kind__: "err";
    err: UpgradeError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PlotUpgradesView_n33(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_UpgradeError_n38(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    TierIII: null;
} | {
    None: null;
} | {
    TierII: null;
} | {
    TierIV: null;
} | {
    TierVI: null;
} | {
    TierI: null;
} | {
    TierV: null;
}): GeneratorTier {
    return "TierIII" in value ? GeneratorTier.TierIII : "None" in value ? GeneratorTier.None : "TierII" in value ? GeneratorTier.TierII : "TierIV" in value ? GeneratorTier.TierIV : "TierVI" in value ? GeneratorTier.TierVI : "TierI" in value ? GeneratorTier.TierI : "TierV" in value ? GeneratorTier.TierV : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SubParcelLocked: null;
} | {
    PlotNotFound: null;
} | {
    InvalidTier: null;
} | {
    NotOwner: null;
} | {
    AlreadyMaxTier: null;
} | {
    InsufficientFRNTR: null;
}): UpgradeError {
    return "SubParcelLocked" in value ? UpgradeError.SubParcelLocked : "PlotNotFound" in value ? UpgradeError.PlotNotFound : "InvalidTier" in value ? UpgradeError.InvalidTier : "NotOwner" in value ? UpgradeError.NotOwner : "AlreadyMaxTier" in value ? UpgradeError.AlreadyMaxTier : "InsufficientFRNTR" in value ? UpgradeError.InsufficientFRNTR : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ResourceType, number]>): Array<[ResourceType, number]> {
    return value.map((x)=>from_candid_tuple_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubParcel>): Array<SubParcel> {
    return value.map((x)=>from_candid_SubParcel_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CombatEvent>): Array<CombatEvent> {
    return value.map((x)=>from_candid_CombatEvent_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StressActionResult>): Array<StressActionResult> {
    return value.map((x)=>from_candid_StressActionResult_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    principal: string;
    username: [] | [string];
    rank: bigint;
    frntBalance: bigint;
    plotsOwned: bigint;
}>): Array<{
    principal: string;
    username?: string;
    rank: bigint;
    frntBalance: bigint;
    plotsOwned: bigint;
}> {
    return value.map((x)=>from_candid_record_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
